apiVersion: v1
kind: Secret
metadata:
  name: loyalty-backend-secret
  labels:
    app: loyalty-backend
type: Opaque
data:
  DB_HOST: {{ .Values.env.db_host | b64enc | default "" | quote }}
  DB_PORT: {{ .Values.env.db_port | b64enc | default "3306" | quote }}
  DB_NAME: {{ .Values.env.db_name | b64enc | default "loyalty_db" | quote }}
  DB_USERNAME: {{ .Values.env.db_username | b64enc | default "root" | quote }}
  DB_PASSWORD: {{ .Values.env.db_password | b64enc | default "" | quote }}

