apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loyalty-mysql-pvc
  labels:
    app: loyalty-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi

