apiVersion: v1
kind: Secret
metadata:
  name: loyalty-db-secret
  labels:
    app: loyalty-db
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=
  mysql-password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: loyalty-db-config
  labels:
    app: loyalty-db
type: Opaque
stringData:
  database: loyalty_db
  host: loyalty-mysql
  port: "3306"
  username: root

