apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-mysql
  labels:
    app: loyalty-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-db
  template:
    metadata:
      labels:
        app: loyalty-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: loyalty-db-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: loyalty_db
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - mysql
                - -h
                - localhost
                - -e
                - SELECT 1
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: loyalty-mysql-pvc
        - name: mysql-config
          configMap:
            name: loyalty-mysql-config

